version: '2'

services:
 
  db:
    image: mattermostdocker_db 
    container_name: db_matter
    volumes:
      - /home/vagrant/volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data 
      - /etc/localtime:/etc/localtime:ro
    # uncomment the following to enable backup
    #environment:
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1
    networks:
      matter_net:
        aliases:
          - db

  app:
    image: mattermostdocker_app
    container_name: app_matter
    ports:
      - "80:80"
      
    volumes:
      - matter_data:/mattermost/config:rw
      - matter_data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      matter_net:
        aliases:
          - app


  hubot:
    image: lessa/hubot-mattermost
    container_name: matterbot
    environment:
      - MATTERMOST_ENDPOINT=/hubot/incoming
      - MATTERMOST_INCOME_URL=http://app/hooks/rtxwh6cbe7y17ndbbuuxm8unfr
      - MATTERMOST_TOKEN=oospbjzs3jdedk86hk85cxh5zw
      - MATTERMOST_ICON_URL=https://s3-eu-west-1.amazonaws.com/renanvicente/toy13.png
      - MATTERMOST_HUBOT_USERNAME=matterbot
      - REDIS_URL=redis://redis-server:6379/hubot
    networks:
     - matter_net
  
  redis:
    image: redis
    container_name: redis-server
    networks:
      - matter_net

volumes:
  matter_data:
    external: true

networks:
  matter_net:
    external: true